name: CI

on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Initializing CICD Pipeline
        uses: actions/checkout@v4

      - name: Setting up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installing dependencies
        run: npm ci

      - name: Linting codebase
        run: |
          npm run lint > lint-output.txt
          echo "### ESLint Summary" >> $GITHUB_STEP_SUMMARY
          cat lint-output.txt | head -n 20 >> $GITHUB_STEP_SUMMARY

      - name: Executing Jest
        run: |
          npm run test > test-output.txt
          echo "### Jest Summary" >> $GITHUB_STEP_SUMMARY
          cat test-output.txt | head -n 20 >> $GITHUB_STEP_SUMMARY

      - name: Building codebase
        run: npm run build
